name: Release
on:
  push:
    branches:
      - 'release/*'

jobs:

  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        id: get_branch
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Update version in package.json
        run: |
          sed -i 's/"version": "[^"]*"/"version": "'${{ env.version }}'"/' package.json


      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GA4_GA_ID: ${{ secrets.GA4_GA_ID }}
          GA4_SECRET: ${{ secrets.GA4_SECRET }}
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
        run: npm run publish

  publish_on_mac:
    name: Publish on macOS (arm64)
    runs-on: macos-latest
    steps:
      - name: Set up Python for appdmg to be installed
        run: brew install python-setuptools

      - uses: actions/checkout@v3
      - name: Get branch name
        id: get_branch
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Update version in package.json
        run: |
          sed -i '' 's/"version": "[^"]*"/"version": "'${{ env.version }}'"/' package.json
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GA4_GA_ID: ${{ secrets.GA4_GA_ID }}
          GA4_SECRET: ${{ secrets.GA4_SECRET }}
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
        run: npm run publish

  publish_on_mac64:
    name: Publish on macOS (Intel based)
    runs-on: macos-13
    steps:
      - name: Set up Python for appdmg to be installed
        run: brew install python-setuptools

      - uses: actions/checkout@v3

      - name: Get branch name
        id: get_branch
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Update version in package.json
        run: |
          sed -i '' 's/"version": "[^"]*"/"version": "'${{ env.version }}'"/' package.json
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: setup appdmg
        run: |
          python3 -m pip install setuptools
          npm install -g appdmg@0.6.6
      - name: install dependencies
        run: npm install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GA4_GA_ID: ${{ secrets.GA4_GA_ID }}
          GA4_SECRET: ${{ secrets.GA4_SECRET }}
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
        run: npm run publish

  publish_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get branch name
        id: get_branch
        run: |
          $branchName = "${GITHUB_REF##*/}"
          echo "branch_name=$branchName" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Update version in package.json
        run: |
          (Get-Content package.json) -replace '"version": "[^"]*"', '"version": "${{ env.branch_name }}"' | Set-Content package.json
        shell: pwsh

      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GA4_GA_ID: ${{ secrets.GA4_GA_ID }}
          GA4_SECRET: ${{ secrets.GA4_SECRET }}
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
        run: npm run publish
